name: RobarCola
version: '1.0-SNAPSHOT'
main: yo.spray.robarCola.RobarCola
api-version: '1.20'

commands:
  giveTail:
    description: Da una cola a un jugador
    usage: /giveCola <jugador>
  setGameSpawn:
    description: Establece el spawn del minijuego
    usage: /robarColaSetSpawn
  setLobby:
    description: Establece el spawn del lobby
    usage: /robarColaSetLobby
  startGame:
    description: Inicia el minijuego manualmente
    usage: /robarColaStartGame
  stopGame:
    description: Detiene el minijuego
    usage: /robarColaStopGame